import 'package:flutter/material.dart';

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF74DF1D),
  onPrimary: Color(0xFF173800),
  primaryContainer: Color(0xFF245100),
  onPrimaryContainer: Color(0xFF8FFD3F),
  secondary: Color(0xFFBECBAF),
  onSecondary: Color(0xFF293420),
  secondaryContainer: Color(0xFF3F4A35),
  onSecondaryContainer: Color(0xFFDAE7CA),
  tertiary: Color(0xFFA0CFCE),
  onTertiary: Color(0xFF003737),
  tertiaryContainer: Color(0xFF1E4E4D),
  onTertiaryContainer: Color(0xFFBBECEA),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1A1C18),
  onBackground: Color(0xFFE3E3DC),
  surface: Color(0xFF1A1C18),
  onSurface: Color(0xFFE3E3DC),
  surfaceVariant: Color(0xFF44483E),
  onSurfaceVariant: Color(0xFFC4C8BB),
  outline: Color(0xFF8E9286),
  onInverseSurface: Color(0xFF1A1C18),
  inverseSurface: Color(0xFFE3E3DC),
  inversePrimary: Color(0xFF326B00),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF74DF1D),
  outlineVariant: Color(0xFF44483E),
  scrim: Color(0xFF000000),
);

final darkTheme = ThemeData(
  scaffoldBackgroundColor: darkColorScheme.background,
  useMaterial3: true,
  colorScheme: darkColorScheme,
  appBarTheme: AppBarTheme(
    centerTitle: true,
    color: darkColorScheme.primaryContainer,
    titleTextStyle: const TextStyle(fontSize: 15),
  ),
);
